global:
  namespace: fhir-lab

ingress:
  enabled: true
  host: fhir.local

hapi:
  image: docker.io/hapiproject/hapi:latest
  replicas: 1
  resources: {{}}
  service:
    type: ClusterIP
    port: 8080
  db:
    host: hapi-postgres
    port: 5432
    name: hapi
    user: admin
    password: admin
  disableHibernateSearch: true

postgresHapi:
  storage: 5Gi
  image: postgres:16
  username: admin
  password: admin
  database: hapi

envoy:
  image: docker.io/envoyproxy/envoy:v1.31.0
  service:
    type: ClusterIP
    port: 8081
  jwt:
    requireAudience: hapi-fhir
    allowWithoutTls: true

keycloak:
  image: quay.io/keycloak/keycloak:24.0.5
  replicas: 1
  adminUser: admin
  adminPassword: admin
  service:
    port: 8080
  realm:
    name: fhir-lab
    clientPublicId: postman-public
    clientConfidentialId: server-confidential
    oauthProxyClientId: oauth2-proxy
    postmanRedirectUri: https://oauth.pstmn.io/v1/callback
    oauthProxyRedirectUri: http://fhir.local/oauth2/callback
  db:
    enabled: true
    image: postgres:16
    username: kc
    password: kcpass
    database: keycloak
  secrets:
    oauthProxyClientSecret: "5U3moHmRZTWsCsoffa7WZm2zosRwEVZW"
    serverClientSecret: "vzFffhwneClffrpxN123qLh-bpv3E-CR"
    cookieSecret: "N5bXQYVsSI4SNs0O5FZwTmfqvbu9T+FHd2PBzENAWys="

oauth2Proxy:
  enabled: false
  image: quay.io/oauth2-proxy/oauth2-proxy:v7.5.1
