apiVersion: v1
kind: ConfigMap
metadata:
  name: hapi-config
  namespace: {{ .Values.global.namespace }}
  labels: { app: hapi-fhir }
data:
  application.yaml: |
    spring:
      datasource:
        url: 'jdbc:postgresql://hapi-postgres.{{ .Values.global.namespace }}.svc.cluster.local:5432/{{ .Values.hapi.db.name }}'
        username: {{ .Values.hapi.db.user }}
        password: {{ .Values.hapi.db.password }}
        driverClassName: org.postgresql.Driver
      jpa:
        properties:
          hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgresDialect
          hibernate.search.enabled: {{ if .Values.hapi.disableHibernateSearch }}false{{ else }}true{{ end }}
    server:
      port: 8080
    hapi:
      fhir:
        fhir_version: R4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hapi-fhir
  namespace: {{ .Values.global.namespace }}
  labels: { app: hapi-fhir }
spec:
  replicas: {{ .Values.hapi.replicas }}
  selector:
    matchLabels: { app: hapi-fhir }
  template:
    metadata:
      labels: { app: hapi-fhir }
    spec:
      containers:
        - name: hapi
          image: {{ .Values.hapi.image }}
          imagePullPolicy: IfNotPresent
          ports: [{ containerPort: 8080 }]
          readinessProbe:
            httpGet: { path: /fhir/metadata, port: 8080 }
            initialDelaySeconds: 40
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /, port: 8080 }
            initialDelaySeconds: 60
            periodSeconds: 20
          volumeMounts:
            - name: hapi-config
              mountPath: /app/config/application.yaml
              subPath: application.yaml
      volumes:
        - name: hapi-config
          configMap: { name: hapi-config }
---
apiVersion: v1
kind: Service
metadata:
  name: hapi-fhir
  namespace: {{ .Values.global.namespace }}
spec:
  selector: { app: hapi-fhir }
  ports:
    - name: http
      port: {{ .Values.hapi.service.port }}
      targetPort: 8080
  type: {{ .Values.hapi.service.type }}
