apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
  namespace: {{ $.Values.global.namespace }}
  labels: { app: oauth2-proxy }
spec:
  replicas: 1
  selector:
    matchLabels: { app: oauth2-proxy }
  template:
    metadata:
      labels: { app: oauth2-proxy }
    spec:
      containers:
        - name: oauth2-proxy
          image: {{ .Values.image }}
          args:
            - "--provider=oidc"
            - "--oidc-issuer-url=http://keycloak.{{ $.Values.global.namespace }}.svc.cluster.local:8080/realms/{{ $.Values.oauth2Proxy.realm }}"
            - "--client-id={{ $.Values.oauth2Proxy.clientId }}"
            - "--client-secret=$(OAUTH2_PROXY_CLIENT_SECRET)"
            - "--cookie-secret=$(COOKIE_SECRET)"
            - "--upstream=http://hapi-fhir.{{ $.Values.global.namespace }}.svc.cluster.local:8080"
            - "--http-address=0.0.0.0:4180"
            - "--cookie-secure=false"           # solo para Minikube (HTTP)
            - "--redirect-url=http://{{ $.Values.oauth2Proxy.host }}/oauth2/callback"
            - "--email-domain=*"
            - "--scope=openid profile email"
          env:
            - name: OAUTH2_PROXY_CLIENT_SECRET
              valueFrom: { secretKeyRef: { name: keycloak-secrets, key: OAUTH_PROXY_CLIENT_SECRET } }
            - name: COOKIE_SECRET
              valueFrom: { secretKeyRef: { name: keycloak-secrets, key: COOKIE_SECRET } }
          ports:
            - containerPort: 4180
---
apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy
  namespace: {{ $.Values.global.namespace }}
spec:
  selector: { app: oauth2-proxy }
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 4180
